### PR TITLE
Always build RPMs for Linux. Fixes #7

### LINKED ISSUE #7: distgo: build RPMs for linux no matter the host OS
Since distgo already enforces building RPMs only for linux-amd64, it should probably pass `-a amd64` and `--rpm-os linux` to fpm so the resulting RPM is usable even if built on OS X (currently when running on OS X it builds me an RPM containing linux-amd64 binaries that is only installable on darwin-amd64 systems)

### PR DESCRIPTION
**Pull request by bmoylan**
This change is [Reviewable](https://reviewable.io/reviews/palantir/godel/58)

### CODE REVIEW

**Comment by bmoylan** [comment]
@nmiyake

**Comment by pjvelez** [comment]
Hey @nmiyake , would you mind cutting a release with this commit in it at some point soon? Would really save me a lot of time deving moving forward. Thanks in advance!

**Comment by nmiyake** [comment]
No problem -- will cut and tag a release this weekend.

**Comment by nmiyake** [comment]
Done -- https://github.com/palantir/godel/releases/tag/0.11.4 is now available and includes this fix.

**Comment by pjvelez** [comment]
Thanks so much @nmiyake! Really appreciate it.

**Pull request merged**
