### PR TITLE
Refactor distgo docker task

### PR DESCRIPTION
**Pull request by yvdinesh**
This change is [Reviewable](https://reviewable.io/reviews/palantir/godel/103)

### CODE REVIEW

**Comment by nmiyake** [comment]
Thanks for the PR! Some requests for changes.

---

Reviewed 89 of 89 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[apps/distgo/cmd/docker/build.go, line 32 at r1](https://reviewable.io:443/reviews/palantir/godel/103#-Khi8siLptgh9s_A7LyO:-Khi8siMFIAYVMyhrcme:bs7l53l) ([raw file](https://github.com/palantir/godel/blob/dda1910ac503d18de30c2c8e6b852df2bbb431ad/apps/distgo/cmd/docker/build.go#L32)):*
> ```Go
> 
> func Build(cfg params.Project, wd string, stdout io.Writer) error {
> 	// build docker dist dependants
> ```

Comment is a bit unclear -- can you clarify what's happening further? Looks like high-level overview is something like "find all products that build Docker images"

---

*[apps/distgo/cmd/docker/build.go, line 47 at r1](https://reviewable.io:443/reviews/palantir/godel/103#-Khi8T7Ar6wXDwXBoBG6:-Khi8T7Ar6wXDwXBoBG7:bhhyz4j) ([raw file](https://github.com/palantir/godel/blob/dda1910ac503d18de30c2c8e6b852df2bbb431ad/apps/distgo/cmd/docker/build.go#L47)):*
> ```Go
> 		products = append(products, product)
> 	}
> 	err := dist.Products(products, cfg, false, wd, stdout)
> ```

Inline operation and error check:

```go
if err := dist.Products(...); err != nil {
// ...
}
```

---

*[apps/distgo/cmd/docker/build.go, line 66 at r1](https://reviewable.io:443/reviews/palantir/godel/103#-Khi9Psvle_M-4RyUakX:-Khi9Psvle_M-4RyUakY:b-90vepl) ([raw file](https://github.com/palantir/godel/blob/dda1910ac503d18de30c2c8e6b852df2bbb431ad/apps/distgo/cmd/docker/build.go#L66)):*
> ```Go
> func RunBuild(buildSpecsWithDeps []params.ProductBuildSpecWithDeps) error {
> 	specsMap := buildSpecsMap(buildSpecsWithDeps)
> 	for productName, productSpecWithDeps := range specsMap {
> ```

Let's sort map keys by name and iterate over them in alphabetical order so that the order in which a given set of products are executed is deterministic (in general, making the ordering of operations like these deterministic is helpful to ensure that, if failures occur, people see them in the same order)

---

*[apps/distgo/cmd/docker/cmd.go, line 26 at r1](https://reviewable.io:443/reviews/palantir/godel/103#-KhiSuCKJiuEOa0cyf46:-KhiSuCKJiuEOa0cyf47:b-89217r) ([raw file](https://github.com/palantir/godel/blob/dda1910ac503d18de30c2c8e6b852df2bbb431ad/apps/distgo/cmd/docker/cmd.go#L26)):*
> ```Go
> 
> func Command() cli.Command {
> ```

Remove unneeded newline

---

*[apps/distgo/cmd/docker/cmd.go, line 42 at r1](https://reviewable.io:443/reviews/palantir/godel/103#-KhiSypG9xmKC9N_OnYv:-KhiSypG9xmKC9N_OnYw:b-clv5jk) ([raw file](https://github.com/palantir/godel/blob/dda1910ac503d18de30c2c8e6b852df2bbb431ad/apps/distgo/cmd/docker/cmd.go#L42)):*
> ```Go
> 	}
> 
> 	publishCmd := cli.Command{
> ```

Minor, but in a case like this you can just do:

```go
return cli.Command{
...
}
```

(basically, don't think that naming the variable and having it separately adds much)

---

*[apps/distgo/params/docker.go, line 73 at r1](https://reviewable.io:443/reviews/palantir/godel/103#-KhiTf0fWByJ-w6LpiPL:-KhiTf0fWByJ-w6LpiPM:b-l61jvg) ([raw file](https://github.com/palantir/godel/blob/dda1910ac503d18de30c2c8e6b852df2bbb431ad/apps/distgo/params/docker.go#L73)):*
> ```Go
> 		return DockerDepDocker, nil
> 	default:
> 		return "", nil
> ```

Default case should return an error

---

*[apps/okgo/generated_src/internal/github.com/palantir/checks/novendor/novendor.go, line 40 at r1](https://reviewable.io:443/reviews/palantir/godel/103#-KhiTsdcfDQcX8-rKnjh:-KhiTsdcfDQcX8-rKnji:b9gey3x) ([raw file](https://github.com/palantir/godel/blob/eb1f8232403bb1292fe1bcbdae87b85913f7f66c/apps/okgo/generated_src/internal/github.com/palantir/checks/novendor/novendor.go#L40)):*
> ```Go
> 	projectPkgFlagName	= "project-package"
> 	fullPathFlagName	= "full"
> 	printPkgInfoFlagName	= "print-pkg-info"
> ```

This shouldn't be part of the change (this is reverting a different change that I made)

---

*[vendor/github.com/docker/docker/api/README.md, line 1 at r1](https://reviewable.io:443/reviews/palantir/godel/103#-KhiU6WhpXDAO1Qlh4Mp:-KhiU6WhpXDAO1Qlh4Mq:b-qulgve) ([raw file](https://github.com/palantir/godel/blob/dda1910ac503d18de30c2c8e6b852df2bbb431ad/vendor/github.com/docker/docker/api/README.md#L1)):*
> ```Markdown
> # Working on the Engine API
> ```

Please manually remove all non-`LICENSE` or `.go` files that were added to the `vendor` directory as part of this commit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/godel/103#-:-KhiUHYiM99KdJUYXpS5:b-yedst1)*

**Comment by yvdinesh** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[apps/distgo/cmd/docker/build.go, line 32 at r1](https://reviewable.io:443/reviews/palantir/godel/103#-Khi8siLptgh9s_A7LyO:-Khw-9OoUyB58D2OCHCp:b-896fix) ([raw file](https://github.com/palantir/godel/blob/dda1910ac503d18de30c2c8e6b852df2bbb431ad/apps/distgo/cmd/docker/build.go#L32)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

Comment is a bit unclear -- can you clarify what's happening further? Looks like high-level overview is something like "find all products that build Docker images"
</blockquote></details>

Done.

---

*[apps/distgo/cmd/docker/build.go, line 47 at r1](https://reviewable.io:443/reviews/palantir/godel/103#-Khi8T7Ar6wXDwXBoBG6:-Khw-Fx8hF_cGUUAIfgY:b-896fix) ([raw file](https://github.com/palantir/godel/blob/dda1910ac503d18de30c2c8e6b852df2bbb431ad/apps/distgo/cmd/docker/build.go#L47)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

Inline operation and error check:

```go
if err := dist.Products(...); err != nil {
// ...
}
```
</blockquote></details>

Done.

---

*[apps/distgo/cmd/docker/build.go, line 66 at r1](https://reviewable.io:443/reviews/palantir/godel/103#-Khi9Psvle_M-4RyUakX:-Khw0U-F-36xQeFdvSEL:b-896fix) ([raw file](https://github.com/palantir/godel/blob/dda1910ac503d18de30c2c8e6b852df2bbb431ad/apps/distgo/cmd/docker/build.go#L66)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

Let's sort map keys by name and iterate over them in alphabetical order so that the order in which a given set of products are executed is deterministic (in general, making the ordering of operations like these deterministic is helpful to ensure that, if failures occur, people see them in the same order)
</blockquote></details>

Done.

---

*[apps/distgo/cmd/docker/cmd.go, line 26 at r1](https://reviewable.io:443/reviews/palantir/godel/103#-KhiSuCKJiuEOa0cyf46:-Khw18_cREhABiVo-Onw:b-896fix) ([raw file](https://github.com/palantir/godel/blob/dda1910ac503d18de30c2c8e6b852df2bbb431ad/apps/distgo/cmd/docker/cmd.go#L26)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

Remove unneeded newline
</blockquote></details>

Done.

---

*[apps/distgo/cmd/docker/cmd.go, line 42 at r1](https://reviewable.io:443/reviews/palantir/godel/103#-KhiSypG9xmKC9N_OnYv:-Khw0d6k1ltjKCku-_YO:b-896fix) ([raw file](https://github.com/palantir/godel/blob/dda1910ac503d18de30c2c8e6b852df2bbb431ad/apps/distgo/cmd/docker/cmd.go#L42)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

Minor, but in a case like this you can just do:

```go
return cli.Command{
...
}
```

(basically, don't think that naming the variable and having it separately adds much)
</blockquote></details>

Done.

---

*[apps/distgo/params/docker.go, line 73 at r1](https://reviewable.io:443/reviews/palantir/godel/103#-KhiTf0fWByJ-w6LpiPL:-Khw0mu0wKe9AGp3xwUk:b-896fix) ([raw file](https://github.com/palantir/godel/blob/dda1910ac503d18de30c2c8e6b852df2bbb431ad/apps/distgo/params/docker.go#L73)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

Default case should return an error
</blockquote></details>

Done.

---

*[apps/okgo/generated_src/internal/github.com/palantir/checks/novendor/novendor.go, line 40 at r1](https://reviewable.io:443/reviews/palantir/godel/103#-KhiTsdcfDQcX8-rKnjh:-Khw7AWi6V1RIJQpHZX3:b-896fix) ([raw file](https://github.com/palantir/godel/blob/eb1f8232403bb1292fe1bcbdae87b85913f7f66c/apps/okgo/generated_src/internal/github.com/palantir/checks/novendor/novendor.go#L40)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

This shouldn't be part of the change (this is reverting a different change that I made)
</blockquote></details>

Done.

---

*[vendor/github.com/docker/docker/api/README.md, line 1 at r1](https://reviewable.io:443/reviews/palantir/godel/103#-KhiU6WhpXDAO1Qlh4Mp:-Khw0sltv7BzHpaK95_F:b-896fix) ([raw file](https://github.com/palantir/godel/blob/dda1910ac503d18de30c2c8e6b852df2bbb431ad/vendor/github.com/docker/docker/api/README.md#L1)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

Please manually remove all non-`LICENSE` or `.go` files that were added to the `vendor` directory as part of this commit.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/godel/103)*

**Comment by yvdinesh** [comment]
Review status: 61 of 121 files reviewed at latest revision, 8 unresolved discussions.

---

*[apps/okgo/generated_src/internal/github.com/palantir/checks/novendor/novendor.go, line 40 at r1](https://reviewable.io:443/reviews/palantir/godel/103#-KhiTsdcfDQcX8-rKnjh:-Khw0tEeiAhZJEpuELOz:bcebpj6) ([raw file](https://github.com/palantir/godel/blob/eb1f8232403bb1292fe1bcbdae87b85913f7f66c/apps/okgo/generated_src/internal/github.com/palantir/checks/novendor/novendor.go#L40)):*
<details><summary><i>Previously, yvdinesh (Dinesh Yeduguru) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This change is being added when running godel verify task.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/godel/103)*

**Comment by nmiyake** [comment]
:lgtm:

---

Reviewed 61 of 79 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/godel/103#-:-Khwx5nNn0lNFkfzyCnF:bnfp4nl)*

**Pull request merged**
