### PR TITLE
Make paths easier to copy.

### PR DESCRIPTION
**Pull request by darora**

### CODE REVIEW

**Comment by nmiyake** [comment]
Looks good, thanks!

**Comment by nmiyake** [comment]
Sorry, looks like I had CircleCI builds on PRs disabled -- updated the settings to fix this. Can you amend/re-push the PR to trigger a build? Just want to verify that there aren't any tests that depend on the current output that will fail with this change.

**Comment by darora** [comment]
Pushed an empty commit

**Comment by nmiyake** [comment]
Great, looks like it's building -- thanks!

**Pull request merged**
