### PR TITLE
Update IDEA command to support Gogland

### PR DESCRIPTION
**Pull request by nmiyake**

### CODE REVIEW

**Comment by bmoylan** [comment]
thanks! sorry I didn't get to this, but I'm happy to try it out.

**Comment by gdearment** [comment]
Would love to try this out, as the latest release of Idea no longer supports go, so i was tricked into moving to gogland

**Comment by nmiyake** [comment]
Same -- that's what pushed me to implement this :)

**Comment by nmiyake** [comment]
Will give another test run locally and if everything checks out I'll tag a release so that projects can bump to this

**Pull request merged**
